# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/proto/common/geometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/proto/common/geometry.proto',
  package='oasis.proto.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"common/proto/common/geometry.proto\x12\x12oasis.proto.common\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"k\n\x0bLineSegment\x12.\n\x08start_pt\x18\x01 \x01(\x0b\x32\x1c.oasis.proto.common.Vector2D\x12,\n\x06\x65nd_pt\x18\x02 \x01(\x0b\x32\x1c.oasis.proto.common.Vector2D\"7\n\x08PointSet\x12+\n\x05point\x18\x01 \x03(\x0b\x32\x1c.oasis.proto.common.Vector2D\"9\n\nPointSet3D\x12+\n\x05point\x18\x01 \x03(\x0b\x32\x1c.oasis.proto.common.Vector3D\"3\n\x04Line\x12+\n\x05point\x18\x01 \x03(\x0b\x32\x1c.oasis.proto.common.Vector2D\"6\n\x07Polygon\x12+\n\x05point\x18\x01 \x03(\x0b\x32\x1c.oasis.proto.common.Vector2D\"i\n\x0eGeneralPolygon\x12*\n\x05outer\x18\x01 \x01(\x0b\x32\x1b.oasis.proto.common.Polygon\x12+\n\x06inners\x18\x02 \x03(\x0b\x32\x1b.oasis.proto.common.Polygonb\x06proto3')
)




_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='oasis.proto.common.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='oasis.proto.common.Vector2D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='oasis.proto.common.Vector2D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=90,
)


_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='oasis.proto.common.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='oasis.proto.common.Vector3D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='oasis.proto.common.Vector3D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='oasis.proto.common.Vector3D.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=135,
)


_QUATERNION = _descriptor.Descriptor(
  name='Quaternion',
  full_name='oasis.proto.common.Quaternion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='oasis.proto.common.Quaternion.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='oasis.proto.common.Quaternion.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='oasis.proto.common.Quaternion.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='oasis.proto.common.Quaternion.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=193,
)


_LINESEGMENT = _descriptor.Descriptor(
  name='LineSegment',
  full_name='oasis.proto.common.LineSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_pt', full_name='oasis.proto.common.LineSegment.start_pt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_pt', full_name='oasis.proto.common.LineSegment.end_pt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=302,
)


_POINTSET = _descriptor.Descriptor(
  name='PointSet',
  full_name='oasis.proto.common.PointSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='oasis.proto.common.PointSet.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=359,
)


_POINTSET3D = _descriptor.Descriptor(
  name='PointSet3D',
  full_name='oasis.proto.common.PointSet3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='oasis.proto.common.PointSet3D.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=418,
)


_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='oasis.proto.common.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='oasis.proto.common.Line.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=471,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='oasis.proto.common.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='point', full_name='oasis.proto.common.Polygon.point', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=527,
)


_GENERALPOLYGON = _descriptor.Descriptor(
  name='GeneralPolygon',
  full_name='oasis.proto.common.GeneralPolygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outer', full_name='oasis.proto.common.GeneralPolygon.outer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inners', full_name='oasis.proto.common.GeneralPolygon.inners', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=634,
)

_LINESEGMENT.fields_by_name['start_pt'].message_type = _VECTOR2D
_LINESEGMENT.fields_by_name['end_pt'].message_type = _VECTOR2D
_POINTSET.fields_by_name['point'].message_type = _VECTOR2D
_POINTSET3D.fields_by_name['point'].message_type = _VECTOR3D
_LINE.fields_by_name['point'].message_type = _VECTOR2D
_POLYGON.fields_by_name['point'].message_type = _VECTOR2D
_GENERALPOLYGON.fields_by_name['outer'].message_type = _POLYGON
_GENERALPOLYGON.fields_by_name['inners'].message_type = _POLYGON
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Quaternion'] = _QUATERNION
DESCRIPTOR.message_types_by_name['LineSegment'] = _LINESEGMENT
DESCRIPTOR.message_types_by_name['PointSet'] = _POINTSET
DESCRIPTOR.message_types_by_name['PointSet3D'] = _POINTSET3D
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['GeneralPolygon'] = _GENERALPOLYGON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2D,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Vector2D)
  ))
_sym_db.RegisterMessage(Vector2D)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Vector3D)
  ))
_sym_db.RegisterMessage(Vector3D)

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), dict(
  DESCRIPTOR = _QUATERNION,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Quaternion)
  ))
_sym_db.RegisterMessage(Quaternion)

LineSegment = _reflection.GeneratedProtocolMessageType('LineSegment', (_message.Message,), dict(
  DESCRIPTOR = _LINESEGMENT,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.LineSegment)
  ))
_sym_db.RegisterMessage(LineSegment)

PointSet = _reflection.GeneratedProtocolMessageType('PointSet', (_message.Message,), dict(
  DESCRIPTOR = _POINTSET,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.PointSet)
  ))
_sym_db.RegisterMessage(PointSet)

PointSet3D = _reflection.GeneratedProtocolMessageType('PointSet3D', (_message.Message,), dict(
  DESCRIPTOR = _POINTSET3D,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.PointSet3D)
  ))
_sym_db.RegisterMessage(PointSet3D)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), dict(
  DESCRIPTOR = _LINE,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Line)
  ))
_sym_db.RegisterMessage(Line)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), dict(
  DESCRIPTOR = _POLYGON,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Polygon)
  ))
_sym_db.RegisterMessage(Polygon)

GeneralPolygon = _reflection.GeneratedProtocolMessageType('GeneralPolygon', (_message.Message,), dict(
  DESCRIPTOR = _GENERALPOLYGON,
  __module__ = 'common.proto.common.geometry_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.GeneralPolygon)
  ))
_sym_db.RegisterMessage(GeneralPolygon)


# @@protoc_insertion_point(module_scope)
