# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/proto/common/meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.proto.common import semantic_type_pb2 as common_dot_proto_dot_common_dot_semantic__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/proto/common/meta.proto',
  package='oasis.proto.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x63ommon/proto/common/meta.proto\x12\x12oasis.proto.common\x1a\'common/proto/common/semantic_type.proto\"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"\x82\x01\n\x04Meta\x12(\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x19.oasis.proto.common.Color\x12\r\n\x05\x61lpha\x18\x02 \x01(\r\x12\x11\n\tintensity\x18\x03 \x01(\x01\x12.\n\x04type\x18\x04 \x01(\x0e\x32 .oasis.proto.common.SemanticTypeb\x06proto3')
  ,
  dependencies=[common_dot_proto_dot_common_dot_semantic__type__pb2.DESCRIPTOR,])




_COLOR = _descriptor.Descriptor(
  name='Color',
  full_name='oasis.proto.common.Color',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='oasis.proto.common.Color.r', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='g', full_name='oasis.proto.common.Color.g', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='oasis.proto.common.Color.b', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=135,
)


_META = _descriptor.Descriptor(
  name='Meta',
  full_name='oasis.proto.common.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='oasis.proto.common.Meta.color', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='oasis.proto.common.Meta.alpha', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='oasis.proto.common.Meta.intensity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='oasis.proto.common.Meta.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=268,
)

_META.fields_by_name['color'].message_type = _COLOR
_META.fields_by_name['type'].enum_type = common_dot_proto_dot_common_dot_semantic__type__pb2._SEMANTICTYPE
DESCRIPTOR.message_types_by_name['Color'] = _COLOR
DESCRIPTOR.message_types_by_name['Meta'] = _META
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Color = _reflection.GeneratedProtocolMessageType('Color', (_message.Message,), dict(
  DESCRIPTOR = _COLOR,
  __module__ = 'common.proto.common.meta_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Color)
  ))
_sym_db.RegisterMessage(Color)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'common.proto.common.meta_pb2'
  # @@protoc_insertion_point(class_scope:oasis.proto.common.Meta)
  ))
_sym_db.RegisterMessage(Meta)


# @@protoc_insertion_point(module_scope)
