# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/proto/common/semantic_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/proto/common/semantic_type.proto',
  package='oasis.proto.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'common/proto/common/semantic_type.proto\x12\x12oasis.proto.common*\xf3\x01\n\x0cSemanticType\x12\n\n\x06OTHERS\x10\x00\x12\x08\n\x04LAWN\x10\x01\x12\x08\n\x04ROAD\x10\x02\x12\x08\n\x04\x42USH\x10\x03\x12\x08\n\x04\x43URB\x10\x04\x12\n\n\x06PEBBLE\x10\x05\x12\r\n\tTREE_ROOT\x10\x06\x12\x08\n\x04LEAF\x10\x07\x12\x0c\n\x08\x42\x41SE_TAG\x10\x14\x12\t\n\x05HUMAN\x10\x15\x12\x07\n\x03\x44OG\x10\x16\x12\x07\n\x03\x43\x41T\x10\x17\x12\x08\n\x04TREE\x10\x18\x12\t\n\x05PLANT\x10\x19\x12\t\n\x05STONE\x10\x1a\x12\x08\n\x04WALL\x10\x1b\x12\t\n\x05\x46\x45NCE\x10\x1c\x12\n\n\x06\x43ORNER\x10x\x12\x10\n\x0cVIRTUAL_ZONE\x10y\x12\x0c\n\x07UNKNOWN\x10\xff\x01\x62\x06proto3')
)

_SEMANTICTYPE = _descriptor.EnumDescriptor(
  name='SemanticType',
  full_name='oasis.proto.common.SemanticType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OTHERS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAWN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROAD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSH', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CURB', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PEBBLE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREE_ROOT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAF', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_TAG', index=8, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HUMAN', index=9, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOG', index=10, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAT', index=11, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREE', index=12, number=24,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLANT', index=13, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STONE', index=14, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WALL', index=15, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FENCE', index=16, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CORNER', index=17, number=120,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIRTUAL_ZONE', index=18, number=121,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=19, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=64,
  serialized_end=307,
)
_sym_db.RegisterEnumDescriptor(_SEMANTICTYPE)

SemanticType = enum_type_wrapper.EnumTypeWrapper(_SEMANTICTYPE)
OTHERS = 0
LAWN = 1
ROAD = 2
BUSH = 3
CURB = 4
PEBBLE = 5
TREE_ROOT = 6
LEAF = 7
BASE_TAG = 20
HUMAN = 21
DOG = 22
CAT = 23
TREE = 24
PLANT = 25
STONE = 26
WALL = 27
FENCE = 28
CORNER = 120
VIRTUAL_ZONE = 121
UNKNOWN = 255


DESCRIPTOR.enum_types_by_name['SemanticType'] = _SEMANTICTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
